apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zrr6sng0e-python 
  janus-idp.io/tekton: zrr6sng0e-python
  backstage.io/kubernetes-id: zrr6sng0e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zrr6sng0e-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml