apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zrr6sng0e-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zrr6sng0e-python 
  name: zrr6sng0e-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zrr6sng0e-python 
